# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-26 13:29
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=140)),
                ('last_name', models.CharField(default='', max_length=140)),
                ('email_address', models.EmailField(default='', max_length=254)),
                ('phone_number', models.CharField(default='', max_length=13, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('origin', models.CharField(default='Colgate', max_length=140)),
                ('destination', models.CharField(max_length=140)),
                ('seats_available', models.PositiveIntegerField(default=0)),
                ('approved', models.BooleanField(default=False)),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='RideRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=140)),
                ('email_address', models.EmailField(default='', max_length=254)),
                ('ride', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ridesharing.Ride')),
            ],
        ),
    ]
