# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-26 12:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ridesharing', '0002_ride_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
