# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-26 14:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ridesharing', '0002_remove_ride_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='date',
            field=models.DateField(default='1996-08-06'),
        ),
    ]
