# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-26 16:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ridesharing', '0002_auto_20170126_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='destination',
            field=models.CharField(default='Colgate', max_length=140),
        ),
    ]
