# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-26 14:05
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ridesharing', '0005_auto_20161226_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='phone_number',
            field=models.CharField(default='', max_length=13, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
