# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-28 10:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ridesharing', '0006_auto_20161226_1405'),
    ]

    operations = [
        migrations.CreateModel(
            name='RideRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=140)),
                ('email_address', models.EmailField(default='', max_length=254)),
                ('ride', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ridesharing.Ride')),
            ],
        ),
    ]
