# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-12 13:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ridesharing', '0007_riderequest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ride',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='ride',
            name='last_name',
            field=models.CharField(default='', max_length=140),
        ),
    ]
