# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-23 16:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ridesharing', '0009_auto_20170115_0914'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='origin',
            field=models.CharField(default='Colgate', max_length=140),
        ),
    ]
